# LIST ALL DATABASES
SHOW DATABASES;
#SWITCH TO A DATABASE USING USE STATEMENT
USE chipotle;
#SHOW CURRENTLY SELECTED DATABASE
SELECT Database();
#SWITCH TO A DIFFERNET DATABASE
USE world;
#SHOW CURRENTLY SELECTED DATABASE
SELECT DATABASE();